# Generated by Django 4.2.17 on 2024-12-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verification_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('forgot_password', 'Forgot Password')], default='signup', max_length=100),
        ),
    ]
