# Generated by Django 4.2.18 on 2025-01-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='creator',
        ),
    ]
