services:

  postgres-db:
    container_name: process_flow_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=process_flow_db
    ports:
    - 5434:5432

  web:
    container_name: process_flow
    build:
      context: .
      dockerfile: ./DockerFile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/process_flow
    ports:
      - 8000:8000
    depends_on:
      - postgres-db

  react-frontend:
    profiles: ["frontend"]
    container_name: process_flow_frontend
    build:
      context: ./web
      dockerfile: DockerFile
    volumes:
      - ./web:/app
      # Let node_modules remain in container by using an anonymous volume:
      - /app/node_modules
    ports:
      - "3000:3000"
    # If you want to ensure the React container waits for the backend or DB, add depends_on
    depends_on:
      - web
  
volumes:
  postgres_data:
