services:

  postgres-db:
    container_name: process_flow_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=process_flow_db
    ports:
    - 5434:5432

  web:
    container_name: process_flow
    build:
      context: .
      dockerfile: ./DockerFile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/process_flow
    ports:
      - 8000:8000
    depends_on:
      - postgres-db

  react-frontend:
    container_name: process_flow_frontend
    build:
      context: ./web
      dockerfile: DockerFile
    volumes:
      - ./web:/app
       - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    stdin_open: true  # Keep container running for hot reloading
    tty: true
    depends_on:
      - web
  
volumes:
  postgres_data: