FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /

RUN apt-get update; apt-get install -y libgl1; apt-get install -y poppler-utils
RUN pip install --no-cache-dir --upgrade pip
RUN pip install -r /requirements.txt

RUN mkdir /eload_be/
WORKDIR /eload_be/
COPY . /eload_be/

RUN adduser --disabled-password --gecos "" django
RUN chown -R django:django /eload_be/

USER django
